### ISSUE TITLE
Suggestions to improve user experience

### ISSUE THREAD

**Issue by patdel0** [fac25/week1-server-sumithra-joe-yassien-suraj#29]
To improve user experience, perhaps we could consider the following:

-  A higher resolution image for the background would render better on larger screens 

- Display new posts at the beginning, to make it easier for the user to confirm the post is actually being posted.

- Currently there is horizontal scroll whenever the plate wrapping the review/description is too big. 
![image](https://user-images.githubusercontent.com/53922624/191796927-240fc0d9-0606-4da4-92c7-8d456c4c1cae.png)

- Consider removing bullet points from the list, because it could be confusing for the user.

**Comment by Joe-Lindie** [comment]
All done :)
