### ISSUE TITLE
Labels are not visible

### ISSUE THREAD

**Issue by alternadiva** [fac25/week1-server-sumithra-joe-yassien-suraj#30]
<img width="533" alt="Screenshot 2022-09-22 at 17 12 39" src="https://user-images.githubusercontent.com/85565743/191798722-182be332-8aee-404e-b0dd-905e06626345.png">

Labels are not showing up in the browser, which could make understanding the purpose of the input fields difficult for the user.

**Comment by Joe-Lindie** [comment]
this was by design so the screen reader would still be able to pick it up.
