### ISSUE TITLE
Improve variable naming

### ISSUE THREAD

**Issue by ivan-unfolds** [fac25/week1-server-sumithra-joe-yassien-suraj#34]
The variable `info` on this line doesn't match what it actually is https://github.com/fac25/week1-server-sumithra-joe-yassien-suraj/blob/bdb69ec793d1bca3eca1c1136b1d588062d41930/src/server.js#L27

May I suggest `body` instead?

**Comment by ivan-unfolds** [comment]
Aside from this though, I loved how clean your `server.js` file was 😍

**Comment by SurPun** [comment]
Thank you, fixed on #36
