### ISSUE TITLE
Improve image naming

### ISSUE THREAD

**Issue by ivan-unfolds** [fac25/week1-server-sumithra-joe-yassien-suraj#35]
One of your images is named `plate` which is great as it's an image of a plate.

The other one is called `bg` which might lead to some issues. At the moment it's used as a background but the design might change soon so that it's used somewhere else and then its name won't make sense. I would suggest changing it to a name that's descriptive of the actual content of the image.

**Comment by SurPun** [comment]
Thank you Ivan, the changes were made on #36
